clear
sleep 1.5
echo -e "$default"
figlet " TermuxButLinux "
echo "| Note: If bash metasploitframework.sh doesn't work, try msfconsole.sh |"
echo "| What would you like to do?                                           |"
echo "| Github: https://github.com/babarich456/TermuxButLinux.git            |"
echo "| bash kalilinux.sh                                                    |"
echo "| bash hydra.sh                                                        |"
echo "| bash nmap.sh                                                         |"
echo "| bash metasploitframework.sh                                          |"
echo "| bash msfconsole.sh                                                   |"
echo "| Write One:                                                           |"
echo "| Example:                                                             |"
echo "| bash nmap.sh                                                         |"
